#pragma once

#include "common/Types.h"
#include "common/ClipboardPayload.h"
#include "rendering/ascii/AsciiAtlas.h"
#include "rendering/ascii/AsciiAtlasBaker.h"
#include "rendering/common/ShaderType.h"
#include "rendering/utility/gl/GLFrameBufferObject.h"
#include "rendering/utility/gl/GLShaderProgram.h"
#include "rendering/utility/gl/GLTexture.h"
#include "rendering/utility/gl/GLVertexArrayObject.h"

#include <glm/vec2.hpp>

#include <array>
#include <functional>
#include <memory>
#include <optional>
#include <string>
#include <unordered_map>
#include <vector>

class AppData;
class View;

/**
 * @brief Owns all ASCII post-processing state and rendering logic.
 *
 * Rendering holds one instance of this class and delegates all ASCII
 * pipeline work (atlas management, FBO management, per-frame draw) here.
 */
class AsciiRenderer
{
public:
  explicit AsciiRenderer(AppData& appData);

  /// Called from Rendering::init() — generates the VAO and builds the atlas.
  void init();

  /// Called from Rendering::createShaderPrograms() — inserts the four ASCII
  /// shader programs into the shared map.
  void registerShaderPrograms(std::unordered_map<ShaderProgramType, std::unique_ptr<GLShaderProgram>>& programs);

  /// Returns true when ASCII mode is on and the atlas texture is ready.
  bool enabled() const;

  /// Called once per frame (before render()) to rebuild the atlas when the
  /// charset changed via the UI.
  void maybeRebuildAtlas();

  using DrawViewFn = std::function<void(const View&, const FrameBounds&, const glm::vec3&)>;

  /**
   * @brief Execute the full ASCII render pipeline for the current frame.
   *
   * @param shaderPrograms  Shared shader program map (owned by Rendering).
   * @param drawImages      Callback that renders image data for one view.
   * @param drawImageBorders Callback that renders image borders for one view.
   * @param drawLandmarks    Callback that renders landmarks for one view.
   * @param drawAnnotations  Callback that renders annotations for one view.
   */
  void render(
    std::unordered_map<ShaderProgramType, std::unique_ptr<GLShaderProgram>>& shaderPrograms,
    DrawViewFn drawImages,
    DrawViewFn drawImageBorders,
    DrawViewFn drawLandmarks,
    DrawViewFn drawAnnotations);

  /**
   * @brief Export the last rendered ASCII clipboard payload for one view.
   *
   * The export uses the current ASCII atlas/charset and the cell-mean texture generated by the most recent ASCII render
   * pass. It returns std::nullopt when ASCII mode has not rendered usable cell data yet.
   */
  std::optional<entropy::ClipboardPayload> exportClipboardPayloadForView(const View& view);

private:
  void buildAtlas();
  void ensureSceneFboSize(glm::ivec2 deviceSize);
  void ensureAsciiCellFbo(glm::ivec2 viewSizeDevPx, glm::vec2 cellSizePxDev);

  AppData& m_appData;

  AsciiAtlas m_asciiAtlas;

  // Scene capture FBO
  GLFrameBufferObject m_sceneFbo;
  std::optional<GLTexture> m_sceneColorTex;
  glm::ivec2 m_sceneFboSize{0, 0};

  // Fullscreen-triangle VAO (no attributes)
  GLVertexArrayObject m_asciiPostVao;

  // Cell-mean downsample FBO
  std::optional<GLTexture> m_asciiCellMeanTex;
  std::optional<GLFrameBufferObject> m_asciiCellMeanFbo;
  glm::ivec2 m_asciiCellMeanTexSize{0, 0};

  // Luminance LUT texture (256×1 R8)
  std::optional<GLTexture> m_asciiLumLutTex;
  glm::vec2 m_asciiLumLutCellPx{0.0f, 0.0f};

  // Spatial glyph-matching state
  std::optional<GLTexture> m_asciiCellRegionsTex;  // RGBA16F, regions 0–3
  std::optional<GLTexture> m_asciiCellRegionsTexB; // RG16F,   regions 4–5
  std::vector<glm::vec4> m_glyphProfilesPackedA;
  std::vector<glm::vec4> m_glyphProfilesPackedB;
  glm::vec2 m_asciiSpatialProfileCellPx{-1.0f, -1.0f};
  std::vector<int> m_glyphRankToIndex;
  float m_asciiSpatialDensityWindow{3.0f};
  std::array<float, kSpatialK> m_glyphRegionMax{};
  float m_lastUploadedExponent{-1.0f};
  std::vector<GlyphProfile> m_glyphProfilesNormalized;
};
