#pragma once

#include "common/Types.h"
#include "common/ClipboardPayload.h"
#include "rendering/ascii/AsciiAtlas.h"
#include "rendering/ascii/AsciiAtlasBaker.h"
#include "rendering/common/ShaderType.h"
#include "rendering/utility/gl/GLFrameBufferObject.h"
#include "rendering/utility/gl/GLShaderProgram.h"
#include "rendering/utility/gl/GLTexture.h"
#include "rendering/utility/gl/GLVertexArrayObject.h"

#include <glm/vec2.hpp>

#include <array>
#include <functional>
#include <memory>
#include <optional>
#include <string>
#include <unordered_map>
#include <vector>

class AppData;
class View;

/**
 * @brief Owns the ASCII post-processing pipeline used to convert rendered views into character-cell output.
 *
 * Rendering keeps one instance of this class and delegates all ASCII-specific work here: glyph atlas construction,
 * shader registration, intermediate framebuffer management, per-frame compositing, and clipboard export. The renderer
 * first captures the normal image pass into an off-screen scene texture, downsamples that texture into ASCII cell data,
 * then composites glyphs back to the default framebuffer.
 */
class AsciiRenderer
{
public:
  /**
   * @brief Create an ASCII renderer bound to application state.
   *
   * @param appData Shared application model used to read render settings, views, layout state, and overlay settings
   */
  explicit AsciiRenderer(AppData& appData);

  /**
   * @brief Initialize OpenGL resources that are independent of the active shader program map.
   *
   * This builds the initial glyph atlas from the selected character set and creates the fullscreen-triangle vertex
   * array used by the ASCII downsample and composite passes. A valid OpenGL context must be current before calling
   * this.
   */
  void init();

  /**
   * @brief Build and insert the ASCII shader programs into the shared rendering shader map.
   *
   * @param programs Shader program map owned by Rendering and indexed by ShaderProgramType
   */
  void registerShaderPrograms(std::unordered_map<ShaderProgramType, std::unique_ptr<GLShaderProgram>>& programs);

  /**
   * @brief Return true when ASCII rendering is enabled and the glyph atlas texture is usable.
   *
   * This is the inexpensive high-level gate used by Rendering before entering the ASCII post-processing path.
   */
  bool enabled() const;

  /**
   * @brief Rebuild the glyph atlas if the user changed the active ASCII character set.
   *
   * The rebuild flag lives in RenderData so UI code can request a rebuild without touching OpenGL resources directly.
   * Call this once per frame before render().
   */
  void maybeRebuildAtlas();

  /**
   * @brief Callback type used to render one view into an ASCII pipeline pass.
   *
   * @param view View being drawn
   * @param frameBounds View bounds in miewport coordinates
   * @param worldXhairsOffset Crosshair offset in world coordinates for the view's current slice
   */
  using DrawViewFn = std::function<void(const View&, const FrameBounds&, const glm::vec3&)>;

  /**
   * @brief Execute the full ASCII render pipeline for the current frame.
   *
   * The method captures the normal image pass into an off-screen texture, computes per-cell averages and optional
   * spatial profiles, composites atlas glyphs back to the window, then draws selected vector overlays on top.
   *
   * @param shaderPrograms Shared shader program map owned by Rendering
   * @param drawImages Callback that renders image data for one view
   * @param drawImageBorders Callback that renders image borders for one view
   * @param drawLandmarks Callback that renders landmarks for one view
   * @param drawAnnotations Callback that renders annotations for one view
   */
  void render(
    std::unordered_map<ShaderProgramType, std::unique_ptr<GLShaderProgram>>& shaderPrograms,
    const DrawViewFn& drawImages,
    const DrawViewFn& drawImageBorders,
    const DrawViewFn& drawLandmarks,
    const DrawViewFn& drawAnnotations);

  /**
   * @brief Export the last rendered ASCII clipboard payload for one view.
   *
   * The export uses the current ASCII atlas and the cell textures generated by the most recent render pass. The
   * returned payload contains plain text, HTML, and RTF representations. Returns std::nullopt when ASCII mode has not
   * rendered usable cell data yet.
   *
   * @param view View whose visible ASCII cells should be copied
   * @return Clipboard payload for the view, or std::nullopt when export data is unavailable
   */
  std::optional<ClipboardPayload> exportClipboardPayloadForView(const View& view);

private:
  /**
   * @brief Build or rebuild the glyph atlas from the active character set.
   *
   * This also invalidates cached luminance and spatial matching textures whose dimensions or glyph ordering depend on
   * the atlas contents.
   */
  void buildAtlas();

  /**
   * @brief Ensure that the full-window scene capture framebuffer matches the current device-pixel window size.
   *
   * @param deviceSize Window size in device pixels
   */
  void ensureSceneFboSize(glm::ivec2 deviceSize);

  /**
   * @brief Ensure that the per-cell downsample framebuffer matches the current view and ASCII cell sizes.
   *
   * @param viewSizeDevPx Full window size in device pixels
   * @param cellSizePxDev ASCII cell size in device pixels
   */
  void ensureAsciiCellFbo(glm::ivec2 viewSizeDevPx, glm::vec2 cellSizePxDev);

  AppData& m_appData; //!< Shared application state; outlives the renderer

  AsciiAtlas m_asciiAtlas; //!< Glyph atlas texture and metadata for the active ASCII character set

  GLFrameBufferObject m_sceneFbo; //!< Off-screen framebuffer used to capture normal image rendering before ASCII
  std::optional<GLTexture> m_sceneColorTex; //!< RGBA scene capture texture attached to m_sceneFbo
  glm::ivec2 m_sceneFboSize{0, 0};          //!< Current scene FBO size in device pixels

  GLVertexArrayObject m_asciiPostVao; //!< Fullscreen-triangle VAO used by ASCII downsample and composite passes

  std::optional<GLTexture> m_asciiCellMeanTex; //!< RGBA16F texture storing one premultiplied color sample per cell
  std::optional<GLFrameBufferObject> m_asciiCellMeanFbo; //!< Framebuffer used to render cell-mean and region textures
  glm::ivec2 m_asciiCellMeanTexSize{0, 0};               //!< Cell texture dimensions in ASCII cells

  std::optional<GLTexture> m_asciiLumLutTex; //!< 256x1 R8 texture mapping luminance bins to glyph density ranks
  glm::vec2 m_asciiLumLutCellPx{0.0f, 0.0f}; //!< Device-pixel cell size used to build m_asciiLumLutTex

  std::optional<GLTexture> m_asciiCellRegionsTex;      //!< RGBA16F per-cell spatial fill texture for regions 0-3
  std::optional<GLTexture> m_asciiCellRegionsTexB;     //!< RG16F per-cell spatial fill texture for regions 4-5
  std::vector<glm::vec4> m_glyphProfilesPackedA;       //!< Packed glyph spatial profiles for regions 0-3
  std::vector<glm::vec4> m_glyphProfilesPackedB;       //!< Packed glyph spatial profiles for regions 4-5
  glm::vec2 m_asciiSpatialProfileCellPx{-1.0f, -1.0f}; //!< Device-pixel cell size used for cached glyph profiles
  std::vector<int> m_glyphRankToIndex;                 //!< Glyph index lookup ordered by luminance density rank
  float m_asciiSpatialDensityWindow{3.0f}; //!< Number of neighboring density ranks searched for spatial matching
  std::array<float, kSpatialK> m_glyphRegionMax{}; //!< Per-region maxima used to normalize spatial profiles
  float m_lastUploadedExponent{-1.0f}; //!< Spatial exponent used for the currently packed glyph profile uniforms
  std::vector<GlyphProfile> m_glyphProfilesNormalized; //!< Normalized unshaped profiles used when exponent changes
};
