#include "ui/ThirdPartyLicenses.h"

#include <cmrc/cmrc.hpp>
#include <imgui/imgui.h>

#include <algorithm>
#include <array>
#include <map>
#include <stdexcept>
#include <string>

CMRC_DECLARE(licenses);

namespace
{

struct LicenseDocument
{
  const char* title;
  const char* resourcePath;
};

struct LicenseEntry
{
  const char* name;
  const char* version;
  const char* source;
  const char* license;
  const char* note;
  const LicenseDocument* documents;
  std::size_t numDocuments;
};

template<std::size_t N>
constexpr std::size_t count(const LicenseDocument (&)[N])
{
  return N;
}

static const LicenseDocument sk_cli11Docs[] = {{"License", "licenses/CLI11.txt"}};
static const LicenseDocument sk_cmakercDocs[] = {{"License", "licenses/CMakeRC.txt"}};
static const LicenseDocument sk_glfwDocs[] = {{"License", "licenses/GLFW.txt"}};
static const LicenseDocument sk_glmDocs[] = {{"License", "licenses/GLM.txt"}};
static const LicenseDocument sk_iconFontDocs[] = {{"License", "licenses/IconFontCppHeaders.txt"}};
static const LicenseDocument sk_imguiDocs[] = {{"License", "licenses/DearImGui.txt"}};
static const LicenseDocument sk_implotDocs[] = {{"License", "licenses/ImPlot.txt"}};
static const LicenseDocument sk_itkDocs[] = {
  {"License", "licenses/Apache-2.0.txt"},
  {"Notice", "licenses/ITK-NOTICE.txt"}};
static const LicenseDocument sk_nanovgDocs[] = {{"License", "licenses/NanoVG.txt"}};
static const LicenseDocument sk_nfdDocs[] = {{"License", "licenses/NativeFileDialogExtended.txt"}};
static const LicenseDocument sk_jsonDocs[] = {{"License", "licenses/nlohmann-json.txt"}};
static const LicenseDocument sk_qtDocs[] = {{"LGPL-3.0-only", "licenses/Qt-LGPL-3.0-only.txt"}};
static const LicenseDocument sk_spdlogDocs[] = {{"License", "licenses/spdlog.txt"}};
static const LicenseDocument sk_stduuidDocs[] = {{"License", "licenses/stduuid.txt"}};
static const LicenseDocument sk_tinyfsmDocs[] = {{"License", "licenses/TinyFSM.txt"}};
static const LicenseDocument sk_gladDocs[] = {{"License", "licenses/GLAD.txt"}};
static const LicenseDocument sk_imguizmoDocs[] = {{"License", "licenses/imGuIZMO.quat.txt"}};
static const LicenseDocument sk_imguiKnobsDocs[] = {{"License", "licenses/imgui-knobs.txt"}};
static const LicenseDocument sk_pnpolyDocs[] = {{"License", "licenses/PNPOLY.txt"}};
static const LicenseDocument sk_safeclibDocs[] = {{"License", "licenses/SafeCLib.txt"}};
static const LicenseDocument sk_tdigestDocs[] = {{"License", "licenses/Apache-2.0.txt"}};
static const LicenseDocument sk_cubicDocs[] = {
  {"License and citation request", "licenses/CubicBSplineInterpolation.txt"}};
static const LicenseDocument sk_cousineDocs[] = {{"License", "licenses/Cousine.txt"}};
static const LicenseDocument sk_forkAwesomeDocs[] = {{"Licenses", "licenses/ForkAwesome.txt"}};
static const LicenseDocument sk_interDocs[] = {{"License", "licenses/Inter.txt"}};
static const LicenseDocument sk_robotoDocs[] = {{"License", "licenses/Roboto.txt"}};
static const LicenseDocument sk_satoshiDocs[] = {{"License", "licenses/Satoshi.txt"}};
static const LicenseDocument sk_spaceGroteskDocs[] = {{"License", "licenses/SpaceGrotesk.txt"}};
static const LicenseDocument sk_supremeDocs[] = {{"License", "licenses/Supreme.txt"}};
static const LicenseDocument sk_peterKovesiDocs[] = {{"License", "licenses/PeterKovesiColourMaps.txt"}};
static const LicenseDocument sk_matplotlibDocs[] = {
  {"Attribution", "licenses/MatplotlibColourMaps.txt"},
  {"CC0-1.0", "licenses/CC0-1.0.txt"}};
static const LicenseDocument sk_cividisDocs[] = {{"License", "licenses/Cividis.txt"}};

static const LicenseEntry sk_entries[] = {
  {"Cividis color map",
   "None",
   "https://www.ncl.ucar.edu/Document/Graphics/ColorTables/cividis.shtml",
   "BSD-3-Clause",
   "",
   sk_cividisDocs,
   count(sk_cividisDocs)},
  {"CLI11", "v2.6.2", "https://github.com/CLIUtils/CLI11", "BSD-3-Clause", "", sk_cli11Docs, count(sk_cli11Docs)},
  {"CMakeRC", "2.0.1", "https://github.com/vector-of-bool/cmrc", "MIT", "", sk_cmakercDocs, count(sk_cmakercDocs)},
  {"Cousine font",
   "None",
   "https://fonts.google.com/specimen/Cousine",
   "Apache License 2.0",
   "",
   sk_cousineDocs,
   count(sk_cousineDocs)},
  {"CUDA Cubic B-Spline Interpolation",
   "None",
   "http://www.dannyruijters.nl/cubicinterpolation/",
   "BSD-3-Clause-style license",
   "The upstream notice requests scientific citation when used in scientific projects.",
   sk_cubicDocs,
   count(sk_cubicDocs)},
  {"Dear ImGui", "v1.92.8", "https://github.com/ocornut/imgui", "MIT", "", sk_imguiDocs, count(sk_imguiDocs)},
  {"Fork Awesome font",
   "None",
   "https://forkaweso.me/Fork-Awesome/",
   "SIL Open Font License 1.1, MIT, and CC-BY-3.0",
   "",
   sk_forkAwesomeDocs,
   count(sk_forkAwesomeDocs)},
  {"GLAD OpenGL loaders",
   "Generated by glad 0.1.33",
   "https://github.com/Dav1dde/glad",
   "MIT and Khronos MIT-style license",
   "",
   sk_gladDocs,
   count(sk_gladDocs)},
  {"GLFW", "3.4", "https://github.com/glfw/glfw", "zlib/libpng", "", sk_glfwDocs, count(sk_glfwDocs)},
  {"GLM", "1.0.3", "https://github.com/g-truc/glm", "Happy Bunny License or MIT", "", sk_glmDocs, count(sk_glmDocs)},
  {"IconFontCppHeaders",
   "210b5a3",
   "https://github.com/juliettef/IconFontCppHeaders",
   "zlib",
   "",
   sk_iconFontDocs,
   count(sk_iconFontDocs)},
  {"imGuIZMO.quat",
   "v3.0",
   "https://github.com/BrutPitt/imGuIZMO.quat",
   "BSD-2-Clause",
   "Includes the Entropy palette button adaptation.",
   sk_imguizmoDocs,
   count(sk_imguizmoDocs)},
  {"imgui-knobs",
   "None",
   "https://github.com/altschuler/imgui-knobs",
   "MIT",
   "",
   sk_imguiKnobsDocs,
   count(sk_imguiKnobsDocs)},
  {"ImPlot", "v0.17", "https://github.com/epezent/implot", "MIT", "", sk_implotDocs, count(sk_implotDocs)},
  {"Insight Toolkit (ITK)",
   "v5.4.3",
   "https://github.com/InsightSoftwareConsortium/ITK",
   "Apache License 2.0",
   "Includes upstream NOTICE text.",
   sk_itkDocs,
   count(sk_itkDocs)},
  {"Inter font",
   "None",
   "https://github.com/rsms/inter",
   "SIL Open Font License 1.1",
   "",
   sk_interDocs,
   count(sk_interDocs)},
  {"Matplotlib viridis, plasma, inferno, and magma color maps",
   "None",
   "https://bids.github.io/colormap/",
   "CC0-1.0",
   "",
   sk_matplotlibDocs,
   count(sk_matplotlibDocs)},
  {"NanoVG", "ce3bf74", "https://github.com/memononen/nanovg", "zlib", "", sk_nanovgDocs, count(sk_nanovgDocs)},
  {"Native File Dialog Extended",
   "v1.3.0",
   "https://github.com/btzy/nativefiledialog-extended",
   "zlib",
   "",
   sk_nfdDocs,
   count(sk_nfdDocs)},
  {"nlohmann::json", "v3.12.0", "https://github.com/nlohmann/json", "MIT", "", sk_jsonDocs, count(sk_jsonDocs)},
  {"Peter Kovesi color maps",
   "2014-2018 copy",
   "https://peterkovesi.com/projects/colourmaps",
   "Creative Commons Attribution 4.0",
   "Attribution text is included in the embedded notice.",
   sk_peterKovesiDocs,
   count(sk_peterKovesiDocs)},
  {"PNPOLY point-in-polygon test",
   "1970-2003 copy",
   "https://wrf.ecse.rpi.edu/Research/Short_Notes/pnpoly.html",
   "BSD-style permissive license",
   "Binary redistribution requires reproducing the copyright notice, conditions, disclaimers, and non-endorsement "
   "term.",
   sk_pnpolyDocs,
   count(sk_pnpolyDocs)},
  {"Qt Base / Qt Core",
   "6.8.1",
   "https://www.qt.io/product/qt6",
   "LGPL-3.0-only",
   "Entropy uses Qt Core as a dynamically linked shared library.",
   sk_qtDocs,
   count(sk_qtDocs)},
  {"Roboto fonts",
   "None",
   "https://fonts.google.com/specimen/Roboto",
   "Apache License 2.0",
   "",
   sk_robotoDocs,
   count(sk_robotoDocs)},
  {"Safe C Library strerrorlen_s fallback",
   "2012-2017 copy",
   "https://github.com/rurban/safeclib",
   "MIT",
   "",
   sk_safeclibDocs,
   count(sk_safeclibDocs)},
  {"Satoshi font",
   "None",
   "https://www.fontshare.com/fonts/satoshi",
   "Fontshare Free Font License",
   "",
   sk_satoshiDocs,
   count(sk_satoshiDocs)},
  {"Space Grotesk font",
   "None",
   "https://github.com/floriankarsten/space-grotesk",
   "SIL Open Font License 1.1",
   "",
   sk_spaceGroteskDocs,
   count(sk_spaceGroteskDocs)},
  {"spdlog", "v1.17.0", "https://github.com/gabime/spdlog", "MIT", "", sk_spdlogDocs, count(sk_spdlogDocs)},
  {"stduuid", "v1.2.3", "https://github.com/mariusbancila/stduuid", "MIT", "", sk_stduuidDocs, count(sk_stduuidDocs)},
  {"Supreme font",
   "None",
   "https://www.fontshare.com/fonts/supreme",
   "Fontshare Free Font License",
   "",
   sk_supremeDocs,
   count(sk_supremeDocs)},
  {"T-Digest for C++",
   "None",
   "https://github.com/derrickburns/tdigest",
   "Apache License 2.0",
   "",
   sk_tdigestDocs,
   count(sk_tdigestDocs)},
  {"TinyFSM", "v1.15.1", "https://github.com/digint/tinyfsm", "MIT", "", sk_tinyfsmDocs, count(sk_tinyfsmDocs)},
};

std::string loadLicenseText(const char* resourcePath)
{
  static std::map<std::string, std::string> cache;

  auto it = cache.find(resourcePath);
  if (it != cache.end()) {
    return it->second;
  }

  const auto fs = cmrc::licenses::get_filesystem();
  try {
    const cmrc::file file = fs.open(resourcePath);
    const std::string text(file.begin(), file.end());
    return cache.emplace(resourcePath, text).first->second;
  }
  catch (const std::runtime_error&) {
    return cache.emplace(resourcePath, std::string{"License resource not found: "} + resourcePath).first->second;
  }
}

void renderReadonlyText(const char* label, const std::string& text)
{
  ImGui::InputTextMultiline(
    label,
    const_cast<char*>(text.c_str()),
    text.size(),
    ImVec2(-FLT_MIN, ImGui::GetTextLineHeight() * 14.0f),
    ImGuiInputTextFlags_ReadOnly);
}

void renderSourceUrl(const LicenseEntry& entry)
{
  ImGui::TextUnformatted("Source:");
  ImGui::SameLine();
  ImGui::TextLinkOpenURL(entry.source, entry.source);
  ImGui::SameLine();
  if (ImGui::SmallButton("Copy URL")) {
    ImGui::SetClipboardText(entry.source);
  }
}

} // namespace

void renderThirdPartyLicenses()
{
  ImGui::TextWrapped(
    "Entropy uses the following external tools, libraries, source snippets, fonts, and color maps. "
    "Each section includes the attribution and license material required for redistribution.");
  ImGui::Spacing();

  ImGui::BeginChild("##externalLicenses", ImVec2(-FLT_MIN, -FLT_MIN), true);

  for (const auto& entry : sk_entries) {
    ImGui::PushID(entry.name);
    if (ImGui::CollapsingHeader(entry.name)) {
      ImGui::Text("Version: %s", entry.version);
      ImGui::Text("License: %s", entry.license);
      renderSourceUrl(entry);
      if (entry.note && entry.note[0] != '\0') {
        ImGui::TextWrapped("%s", entry.note);
      }

      ImGui::Spacing();
      for (std::size_t i = 0; i < entry.numDocuments; ++i) {
        const auto& doc = entry.documents[i];
        ImGui::Text("%s", doc.title);
        const std::string label = std::string("##") + entry.name + doc.title;
        renderReadonlyText(label.c_str(), loadLicenseText(doc.resourcePath));
        ImGui::Spacing();
      }
    }
    ImGui::PopID();
  }

  ImGui::EndChild();
}
