#include "rendering/ShaderInfoSetup.h"

namespace rendering::shader_setup
{

std::vector<ShaderProgramType> buildShaderTypeList()
{
  return {
    ShaderProgramType::ImageGrayLinear,
    ShaderProgramType::ImageGrayLinearFloating,
    ShaderProgramType::ImageGrayCubic,
    ShaderProgramType::ImageGrayLinearWarped,
    ShaderProgramType::ImageGrayLinearFloatingWarped,
    ShaderProgramType::ImageGrayCubicWarped,
    ShaderProgramType::ImageColorLinear,
    ShaderProgramType::ImageColorCubic,
    ShaderProgramType::ImageColorLinearWarped,
    ShaderProgramType::ImageColorCubicWarped,
    ShaderProgramType::VectorDirectionColorLinear,
    ShaderProgramType::VectorDirectionColorCubic,
    ShaderProgramType::VectorSignedNormalProjectionLinear,
    ShaderProgramType::VectorSignedNormalProjectionCubic,
    ShaderProgramType::VectorPlanarProjectionColorLinear,
    ShaderProgramType::VectorPlanarProjectionColorCubic,
    ShaderProgramType::VectorWarpedGridLinear,
    ShaderProgramType::VectorWarpedGridCubic,
    ShaderProgramType::EdgeSobelLinear,
    ShaderProgramType::EdgeSobelCubic,
    ShaderProgramType::EdgeSobelLinearWarped,
    ShaderProgramType::EdgeSobelCubicWarped,
    ShaderProgramType::XrayLinear,
    ShaderProgramType::XrayCubic,
    ShaderProgramType::XrayLinearWarped,
    ShaderProgramType::XrayCubicWarped,
    ShaderProgramType::SegmentationNearest,
    ShaderProgramType::SegmentationLinear,
    ShaderProgramType::SegmentationNearestWarped,
    ShaderProgramType::SegmentationLinearWarped,
    ShaderProgramType::IsoContourLinearFloating,
    ShaderProgramType::IsoContourLinearFixed,
    ShaderProgramType::IsoContourCubicFixed,
    ShaderProgramType::IsoContourLinearFloatingWarped,
    ShaderProgramType::IsoContourLinearFixedWarped,
    ShaderProgramType::IsoContourCubicFixedWarped,
    ShaderProgramType::DifferenceLinear,
    ShaderProgramType::DifferenceCubic,
    ShaderProgramType::DifferenceLinearWarped,
    ShaderProgramType::DifferenceCubicWarped,
    ShaderProgramType::LocalNccLinear,
    ShaderProgramType::LocalNccCubic,
    ShaderProgramType::LocalNccLinearWarped,
    ShaderProgramType::LocalNccCubicWarped,
    ShaderProgramType::LocalLinearResidualLinear,
    ShaderProgramType::LocalLinearResidualCubic,
    ShaderProgramType::LocalLinearResidualLinearWarped,
    ShaderProgramType::LocalLinearResidualCubicWarped,
    ShaderProgramType::OverlapLinear,
    ShaderProgramType::OverlapCubic,
    ShaderProgramType::OverlapLinearWarped,
    ShaderProgramType::OverlapCubicWarped};
}

std::unordered_map<ShaderProgramType, ShaderInfo> buildShaderInfoMap(
  const ShaderSourceSet& sources,
  const ShaderUniformSet& uniforms)
{
  return {
    {ShaderProgramType::ImageGrayLinear,
     {"Image.vs",
      "ImageGrey.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$COLOR_HELPER_FUNCTIONS$$", sources.colorHelpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordIdentity},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender},
       {"$$IP_FUNCTION$$", sources.intensityProjection}},
      uniforms.vsImageUniforms,
      uniforms.fsImageGrayUniforms}},
    {ShaderProgramType::ImageGrayLinearFloating,
     {"Image.vs",
      "ImageGrey.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$COLOR_HELPER_FUNCTIONS$$", sources.colorHelpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureFloatingPointLinear3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordIdentity},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender},
       {"$$IP_FUNCTION$$", sources.intensityProjection}},
      uniforms.vsImageUniforms,
      uniforms.fsImageGrayUniforms}},
    {ShaderProgramType::ImageGrayCubic,
     {"Image.vs",
      "ImageGrey.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$COLOR_HELPER_FUNCTIONS$$", sources.colorHelpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordIdentity},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender},
       {"$$IP_FUNCTION$$", sources.intensityProjection}},
      uniforms.vsImageUniforms,
      uniforms.fsImageGrayUniforms}},
    {ShaderProgramType::ImageGrayLinearWarped,
     {"ImageWarped.vs",
      "ImageGrey.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$COLOR_HELPER_FUNCTIONS$$", sources.colorHelpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordDeformation},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender},
       {"$$IP_FUNCTION$$", sources.intensityProjection}},
      uniforms.vsImageWarpedUniforms,
      uniforms.fsImageGrayWarpedUniforms}},
    {ShaderProgramType::ImageGrayLinearFloatingWarped,
     {"ImageWarped.vs",
      "ImageGrey.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$COLOR_HELPER_FUNCTIONS$$", sources.colorHelpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureFloatingPointLinear3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordDeformation},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender},
       {"$$IP_FUNCTION$$", sources.intensityProjection}},
      uniforms.vsImageWarpedUniforms,
      uniforms.fsImageGrayWarpedUniforms}},
    {ShaderProgramType::ImageGrayCubicWarped,
     {"ImageWarped.vs",
      "ImageGrey.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$COLOR_HELPER_FUNCTIONS$$", sources.colorHelpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordDeformation},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender},
       {"$$IP_FUNCTION$$", sources.intensityProjection}},
      uniforms.vsImageWarpedUniforms,
      uniforms.fsImageGrayWarpedUniforms}},
    {ShaderProgramType::ImageColorLinear,
     {"Image.vs",
      "ImageColor.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$COLOR_HELPER_FUNCTIONS$$", sources.colorHelpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordIdentity},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageUniforms,
      uniforms.fsImageColorUniforms}},
    {ShaderProgramType::ImageColorCubic,
     {"Image.vs",
      "ImageColor.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordIdentity},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageUniforms,
      uniforms.fsImageColorUniforms}},
    {ShaderProgramType::ImageColorLinearWarped,
     {"ImageWarped.vs",
      "ImageColor.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$COLOR_HELPER_FUNCTIONS$$", sources.colorHelpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordDeformation},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageWarpedUniforms,
      uniforms.fsImageColorWarpedUniforms}},
    {ShaderProgramType::ImageColorCubicWarped,
     {"ImageWarped.vs",
      "ImageColor.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordDeformation},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageWarpedUniforms,
      uniforms.fsImageColorWarpedUniforms}},
    {ShaderProgramType::VectorDirectionColorLinear,
     {"Image.vs",
      "VectorDirectionColor.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageUniforms,
      uniforms.fsVectorDirectionColorUniforms}},
    {ShaderProgramType::VectorDirectionColorCubic,
     {"Image.vs",
      "VectorDirectionColor.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageUniforms,
      uniforms.fsVectorDirectionColorUniforms}},
    {ShaderProgramType::VectorSignedNormalProjectionLinear,
     {"Image.vs",
      "VectorSignedNormalProjection.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageUniforms,
      uniforms.fsVectorSignedNormalProjectionUniforms}},
    {ShaderProgramType::VectorSignedNormalProjectionCubic,
     {"Image.vs",
      "VectorSignedNormalProjection.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageUniforms,
      uniforms.fsVectorSignedNormalProjectionUniforms}},
    {ShaderProgramType::VectorPlanarProjectionColorLinear,
     {"Image.vs",
      "VectorPlanarProjectionColor.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageUniforms,
      uniforms.fsVectorPlanarProjectionColorUniforms}},
    {ShaderProgramType::VectorPlanarProjectionColorCubic,
     {"Image.vs",
      "VectorPlanarProjectionColor.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageUniforms,
      uniforms.fsVectorPlanarProjectionColorUniforms}},
    {ShaderProgramType::VectorWarpedGridLinear,
     {"Image.vs",
      "VectorWarpedGrid.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageUniforms,
      uniforms.fsVectorWarpedGridUniforms}},
    {ShaderProgramType::VectorWarpedGridCubic,
     {"Image.vs",
      "VectorWarpedGrid.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageUniforms,
      uniforms.fsVectorWarpedGridUniforms}},
    {ShaderProgramType::EdgeSobelLinear,
     {"Image.vs",
      "Edge.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$COLOR_HELPER_FUNCTIONS$$", sources.colorHelpers},
       {"$$COMPUTE_EDGE_FUNCTION$$", sources.edgeSobel},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordIdentity},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageUniforms,
      uniforms.fsEdgeUniforms}},
    {ShaderProgramType::EdgeSobelCubic,
     {"Image.vs",
      "Edge.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$COLOR_HELPER_FUNCTIONS$$", sources.colorHelpers},
       {"$$COMPUTE_EDGE_FUNCTION$$", sources.edgeSobel},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordIdentity},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageUniforms,
      uniforms.fsEdgeUniforms}},
    {ShaderProgramType::EdgeSobelLinearWarped,
     {"ImageWarped.vs",
      "Edge.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$COLOR_HELPER_FUNCTIONS$$", sources.colorHelpers},
       {"$$COMPUTE_EDGE_FUNCTION$$", sources.edgeSobel},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordDeformation},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageWarpedUniforms,
      uniforms.fsEdgeWarpedUniforms}},
    {ShaderProgramType::EdgeSobelCubicWarped,
     {"ImageWarped.vs",
      "Edge.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$COLOR_HELPER_FUNCTIONS$$", sources.colorHelpers},
       {"$$COMPUTE_EDGE_FUNCTION$$", sources.edgeSobel},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordDeformation},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageWarpedUniforms,
      uniforms.fsEdgeWarpedUniforms}},
    {ShaderProgramType::XrayLinear,
     {"Image.vs",
      "Xray.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$COLOR_HELPER_FUNCTIONS$$", sources.colorHelpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordIdentity},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageUniforms,
      uniforms.fsXrayUniforms}},
    {ShaderProgramType::XrayCubic,
     {"Image.vs",
      "Xray.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$COLOR_HELPER_FUNCTIONS$$", sources.colorHelpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordIdentity},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageUniforms,
      uniforms.fsXrayUniforms}},
    {ShaderProgramType::XrayLinearWarped,
     {"ImageWarped.vs",
      "Xray.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$COLOR_HELPER_FUNCTIONS$$", sources.colorHelpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordDeformation},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageWarpedUniforms,
      uniforms.fsXrayWarpedUniforms}},
    {ShaderProgramType::XrayCubicWarped,
     {"ImageWarped.vs",
      "Xray.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$COLOR_HELPER_FUNCTIONS$$", sources.colorHelpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordDeformation},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageWarpedUniforms,
      uniforms.fsXrayWarpedUniforms}},
    {ShaderProgramType::SegmentationNearest,
     {"Seg.vs",
      "Seg.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$UINT_TEXTURE_LOOKUP_FUNCTION$$", sources.uintTextureLinear3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordIdentity},
       {"$$GET_SEG_VALUE_FUNCTION$$", sources.segValueNearest},
       {"$$GET_SEG_INTERIOR_ALPHA_FUNCTION$$", sources.segInteriorAlphaWithOutline},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsSegUniforms,
      uniforms.fsSegNearestUniforms}},
    {ShaderProgramType::SegmentationLinear,
     {"Seg.vs",
      "Seg.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$UINT_TEXTURE_LOOKUP_FUNCTION$$", sources.uintTextureLinear3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordIdentity},
       {"$$GET_SEG_VALUE_FUNCTION$$", sources.segValueLinear},
       {"$$GET_SEG_INTERIOR_ALPHA_FUNCTION$$", sources.segInteriorAlphaWithOutline},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsSegUniforms,
      uniforms.fsSegLinearUniforms}},
    {ShaderProgramType::SegmentationNearestWarped,
     {"SegWarped.vs",
      "Seg.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$UINT_TEXTURE_LOOKUP_FUNCTION$$", sources.uintTextureLinear3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordDeformation},
       {"$$GET_SEG_VALUE_FUNCTION$$", sources.segValueNearest},
       {"$$GET_SEG_INTERIOR_ALPHA_FUNCTION$$", sources.segInteriorAlphaWithOutline},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsSegWarpedUniforms,
      uniforms.fsSegNearestWarpedUniforms}},
    {ShaderProgramType::SegmentationLinearWarped,
     {"SegWarped.vs",
      "Seg.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$UINT_TEXTURE_LOOKUP_FUNCTION$$", sources.uintTextureLinear3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordDeformation},
       {"$$GET_SEG_VALUE_FUNCTION$$", sources.segValueLinear},
       {"$$GET_SEG_INTERIOR_ALPHA_FUNCTION$$", sources.segInteriorAlphaWithOutline},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsSegWarpedUniforms,
      uniforms.fsSegLinearWarpedUniforms}},
    {ShaderProgramType::IsoContourLinearFloating,
     {"Image.vs",
      "IsoContour.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureFloatingPointLinear3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordIdentity},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageUniforms,
      uniforms.fsIsoUniforms}},
    {ShaderProgramType::IsoContourLinearFixed,
     {"Image.vs",
      "IsoContour.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordIdentity},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageUniforms,
      uniforms.fsIsoUniforms}},
    {ShaderProgramType::IsoContourCubicFixed,
     {"Image.vs",
      "IsoContour.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordIdentity},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageUniforms,
      uniforms.fsIsoUniforms}},
    {ShaderProgramType::IsoContourLinearFloatingWarped,
     {"ImageWarped.vs",
      "IsoContour.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureFloatingPointLinear3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordDeformation},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageWarpedUniforms,
      uniforms.fsIsoWarpedUniforms}},
    {ShaderProgramType::IsoContourLinearFixedWarped,
     {"ImageWarped.vs",
      "IsoContour.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordDeformation},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageWarpedUniforms,
      uniforms.fsIsoWarpedUniforms}},
    {ShaderProgramType::IsoContourCubicFixedWarped,
     {"ImageWarped.vs",
      "IsoContour.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$SAMPLE_TEX_COORD_FUNCTION$$", sources.sampleTexCoordDeformation},
       {"$$DO_RENDER_FUNCTION$$", sources.doRender}},
      uniforms.vsImageWarpedUniforms,
      uniforms.fsIsoWarpedUniforms}},
    {ShaderProgramType::DifferenceLinear,
     {"Metric.vs",
      "Difference.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$METRIC_SAMPLING_FUNCTIONS$$", sources.metricSamplingIdentity}},
      uniforms.vsMetricUniforms,
      uniforms.fsDiffUniforms}},
    {ShaderProgramType::DifferenceCubic,
     {"Metric.vs",
      "Difference.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$METRIC_SAMPLING_FUNCTIONS$$", sources.metricSamplingIdentity}},
      uniforms.vsMetricUniforms,
      uniforms.fsDiffUniforms}},
    {ShaderProgramType::DifferenceLinearWarped,
     {"MetricWarped.vs",
      "Difference.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$METRIC_SAMPLING_FUNCTIONS$$", sources.metricSamplingDeformation}},
      uniforms.vsMetricWarpedUniforms,
      uniforms.fsDiffWarpedUniforms}},
    {ShaderProgramType::DifferenceCubicWarped,
     {"MetricWarped.vs",
      "Difference.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$METRIC_SAMPLING_FUNCTIONS$$", sources.metricSamplingDeformation}},
      uniforms.vsMetricWarpedUniforms,
      uniforms.fsDiffWarpedUniforms}},
    {ShaderProgramType::LocalNccLinear,
     {"Metric.vs",
      "LocalNcc.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$METRIC_SAMPLING_FUNCTIONS$$", sources.metricSamplingIdentity}},
      uniforms.vsMetricUniforms,
      uniforms.fsLocalNccUniforms}},
    {ShaderProgramType::LocalNccCubic,
     {"Metric.vs",
      "LocalNcc.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$METRIC_SAMPLING_FUNCTIONS$$", sources.metricSamplingIdentity}},
      uniforms.vsMetricUniforms,
      uniforms.fsLocalNccUniforms}},
    {ShaderProgramType::LocalNccLinearWarped,
     {"MetricWarped.vs",
      "LocalNcc.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$METRIC_SAMPLING_FUNCTIONS$$", sources.metricSamplingDeformation}},
      uniforms.vsMetricWarpedUniforms,
      uniforms.fsLocalNccWarpedUniforms}},
    {ShaderProgramType::LocalNccCubicWarped,
     {"MetricWarped.vs",
      "LocalNcc.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$METRIC_SAMPLING_FUNCTIONS$$", sources.metricSamplingDeformation}},
      uniforms.vsMetricWarpedUniforms,
      uniforms.fsLocalNccWarpedUniforms}},
    {ShaderProgramType::LocalLinearResidualLinear,
     {"Metric.vs",
      "LocalLinearResidual.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$METRIC_SAMPLING_FUNCTIONS$$", sources.metricSamplingIdentity}},
      uniforms.vsMetricUniforms,
      uniforms.fsLocalLinearResidualUniforms}},
    {ShaderProgramType::LocalLinearResidualCubic,
     {"Metric.vs",
      "LocalLinearResidual.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$METRIC_SAMPLING_FUNCTIONS$$", sources.metricSamplingIdentity}},
      uniforms.vsMetricUniforms,
      uniforms.fsLocalLinearResidualUniforms}},
    {ShaderProgramType::LocalLinearResidualLinearWarped,
     {"MetricWarped.vs",
      "LocalLinearResidual.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$METRIC_SAMPLING_FUNCTIONS$$", sources.metricSamplingDeformation}},
      uniforms.vsMetricWarpedUniforms,
      uniforms.fsLocalLinearResidualWarpedUniforms}},
    {ShaderProgramType::LocalLinearResidualCubicWarped,
     {"MetricWarped.vs",
      "LocalLinearResidual.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$METRIC_SAMPLING_FUNCTIONS$$", sources.metricSamplingDeformation}},
      uniforms.vsMetricWarpedUniforms,
      uniforms.fsLocalLinearResidualWarpedUniforms}},
    {ShaderProgramType::OverlapLinear,
     {"Metric.vs",
      "Overlay.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$METRIC_SAMPLING_FUNCTIONS$$", sources.metricSamplingIdentity}},
      uniforms.vsMetricUniforms,
      uniforms.fsOverlayUniforms}},
    {ShaderProgramType::OverlapCubic,
     {"Metric.vs",
      "Overlay.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$METRIC_SAMPLING_FUNCTIONS$$", sources.metricSamplingIdentity}},
      uniforms.vsMetricUniforms,
      uniforms.fsOverlayUniforms}},
    {ShaderProgramType::OverlapLinearWarped,
     {"MetricWarped.vs",
      "Overlay.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureLinear3D},
       {"$$METRIC_SAMPLING_FUNCTIONS$$", sources.metricSamplingDeformation}},
      uniforms.vsMetricWarpedUniforms,
      uniforms.fsOverlayWarpedUniforms}},
    {ShaderProgramType::OverlapCubicWarped,
     {"MetricWarped.vs",
      "Overlay.fs",
      {{"$$HELPER_FUNCTIONS$$", sources.helpers},
       {"$$TEXTURE_LOOKUP_FUNCTION$$", sources.textureCubic3D},
       {"$$METRIC_SAMPLING_FUNCTIONS$$", sources.metricSamplingDeformation}},
      uniforms.vsMetricWarpedUniforms,
      uniforms.fsOverlayWarpedUniforms}}};
}

} // namespace rendering::shader_setup
