#pragma once

#include <iostream>

enum class ShaderProgramType
{
  ImageGrayLinear,
  ImageGrayLinearFloating,
  ImageGrayCubic,
  ImageGrayLinearWarped,
  ImageGrayLinearFloatingWarped,
  ImageGrayCubicWarped,
  ImageColorLinear,
  ImageColorCubic,
  ImageColorLinearWarped,
  ImageColorCubicWarped,
  VectorDirectionColorLinear,
  VectorDirectionColorCubic,
  VectorSignedNormalProjectionLinear,
  VectorSignedNormalProjectionCubic,
  VectorPlanarProjectionColorLinear,
  VectorPlanarProjectionColorCubic,
  VectorWarpedGridLinear,
  VectorWarpedGridCubic,
  EdgeSobelLinear,
  EdgeSobelCubic,
  EdgeSobelLinearWarped,
  EdgeSobelCubicWarped,
  XrayLinear,
  XrayCubic,
  XrayLinearWarped,
  XrayCubicWarped,
  SegmentationNearest,
  SegmentationLinear,
  SegmentationNearestWarped,
  SegmentationLinearWarped,
  IsoContourLinearFloating,
  IsoContourLinearFixed,
  IsoContourCubicFixed,
  IsoContourLinearFloatingWarped,
  IsoContourLinearFixedWarped,
  IsoContourCubicFixedWarped,
  DifferenceLinear,
  DifferenceCubic,
  DifferenceLinearWarped,
  DifferenceCubicWarped,
  LocalNccLinear,
  LocalNccCubic,
  LocalNccLinearWarped,
  LocalNccCubicWarped,
  LocalLinearResidualLinear,
  LocalLinearResidualCubic,
  LocalLinearResidualLinearWarped,
  LocalLinearResidualCubicWarped,
  OverlapLinear,
  OverlapCubic,
  OverlapLinearWarped,
  OverlapCubicWarped,
  AsciiPost,
  AsciiCellMean,
  AsciiCellRegions,
  AsciiPostSpatial,
  PixelEdgePost
};

std::string to_string(ShaderProgramType type);
std::ostream& operator<<(std::ostream& os, ShaderProgramType type);
